---
- name: 'Remove Old Kernels on Ubuntu/Debian hosts'
  hosts: '{{ target_hosts }}'   # pass variable hosts from Ansible inventory
  become: true
  become_user: root
  tasks:
    - name: 'Uninstall'
      ansible.builtin.shell:
        cmd: echo $(dpkg --list | grep linux-image | awk '{ print $2 }' | sort -V | sed -n '/'`uname -r`'/q;p') $(dpkg --list | grep linux-headers | awk '{ print $2 }' | sort -V | sed -n '/'"$(uname -r | sed "s/\([0-9.-]*\)-\([^0-9]\+\)/\1/")"'/q;p') | xargs sudo apt-get -y purge