---
- name: 'Restart Windows hosts'
  hosts: '{{ target_hosts }}'   # pass variable hosts from Ansible inventory
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: 'Restart'
      win_reboot: